"Bundle 'Valloric/YouCompleteMe'
"Based On:
" 	Amir Salihefendic's .vimrc version 5.0 -29/05/12 15:43:36
" 	
" Modifier:
" 	Liu Yang
" 	JeremyRobturtle@gmail.com
"
" Blog_post:
" 	http://amix.dk/blog/post/19691#The-ultimate-Vim-configuration-on-Github 
" Awesome_version:
" 	https://github.com/amix/vimrc
"
" Sections:
" 	-> General
" 	-> VIM user interface
" 	-> Colors and Fonts
" 	-> Files and backups
"	-> Text, tab and indent related
"	-> Visual mode related
"	-> Moving around, tabs and buffers
"	-> Status line
"	-> Editing mappings
"	-> vimgrep searching and cope displaying
"	-> Spell checking
"	-> Misc
"	-> Helper functions
"	-> Plugins configurations
"
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""
" => General
"""""""""""""""""""""""""""""""""""
" Set utf8 as standard encoding and en_US as the standard language
"
set encoding=utf8
" Sets how many lines of history VIM has to remember
set history=700
" Set to auto read when a file is changed from the outside
set autoread
" With a map leader it's possible to do extra key combinations
let mapleader = ","
let g:mapleader = ","
" Fast saving
nnoremap <leader>w :w!<cr>
set ruler

"""""""""""""""""""""""""""""""""""
" => VIM user interface
""""""""""""""""""""""""""""""""""""
"设置文件编码
"13
"set fileencodings=utf-8,cp936,chinese,latin-1,ucs-bom,gb18030,big5,euc-jp,euc-kr,latin1,gbk,gb2321
set fileencodings=ucs-bom,chinese,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1

" Set lines to the cursor - when moving vertically using j/k
set so=7
" Turn on the Wild menu
set wildmenu

" Ignore compiled files
set wildignore=*.o,*~,*.pyc,*.bin,#*#
if has("win16") || has("win32")
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
else
    set wildignore+=.git\*,.hg\*,.svn\*
endif

"Always show current position
set ruler

" A buffer becomes hidden when it is abandoned
set hid
" Configure backspaces so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l
" Ignore case when searching
set ignorecase
" When searching try to be smart about cases
set smartcase
" Highlight search results
set hlsearch
" Makes search act like search in modern browsers
set incsearch
" For regular expressions turn magic on
set magic
" Show matching brackets when text indicator is over them
set showmatch
" How many tenths of a second to blink when matching brackets
set mat=2
" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500
" Set line's number
set nu
"set relativenumber

" Set fold method and don't fold it on default
set fdm=syntax
"set foldlevel=99

"""""""""""""""""""""""""""""""""""
" => Colors and Fonts
"""""""""""""""""""""""""""""""""""
" Enable syntax highlighting
syntax enable
set background=dark

try
    colorscheme desert
    "colorscheme solarized
catch
endtry

" Set extra options when running in GUI mode
if has("gui_running")
    set guioptions-=T
    set guioptions+=e
    set t_Co=256
    set guitablabel=%M\ %t
endif

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Different background color over 80 chars
"FIXME always RED in iTerm2. Probably related with an outter colorscheme
highlight ColorColumn ctermbg=LightGreen guibg=#2c2d27
" Because the bug above, only highlight column 80
"let &colorcolumn="80,".join(range(120,999),",")
let &colorcolumn="80"

"""""""""""""""""""""""""""""""""""
" => Files, backups and undo
"""""""""""""""""""""""""""""""""""
filetype plugin indent off
" Turn backup off, since most stuff is in SVN, git etc anyway
set nobackup
set nowb
set noswapfile

augroup set_filetype
    " Set filetype for .zsh/rc/*.rc
    au BufRead,BufNewFile */.zsh/rc/*.rc setf zsh
    au BufRead,BufNewFile *.h++ setf cpp
    au BufRead,BufNewFile *.c++ setf cpp
    " highlight for .xinitrc
    au BufRead,BufNewFile .xinitrc setf sh
    au BufRead,BufNewFile *.mm setf xml
    au BufRead,BufNewFile *.sc setf scala
augroup END

" Enable filetype plugins
filetype plugin indent on

augroup set_html
    " Auto format markup languages
    au BufWritePre,BufRead *.html,*.htm,*.xml,*.mm :normal mzgg=G`z
    " No wrap for markup languages
    au BufRead,BufNewFile *.html,*.htm,*.xml,*.mm :setlocal nowrap
augroup END

"""""""""""""""""""""""""""""""""""
" => Text, tab and indent related
"""""""""""""""""""""""""""""""""""
" Be smart when using tabs ;)
set smarttab
" 1 tab == 4 spaces
set shiftwidth=4
set tabstop=4
set expandtab
" Linebreak on 500 characters
set lbr
set tw=500
set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

"""""""""""""""""""""""""""""""""""
" => Moving around, tabs, windows and buffers
"""""""""""""""""""""""""""""""""""
" Treat long lines as break lines (useful when moving around in them!)
nnoremap j gj
nnoremap k gk

" Disable hightlight when <leader><cr> is pressed
nnoremap <silent> <leader><space> :noh<cr>:pc<cr>

" Smart way to move between windows
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-h> <C-W>h
nnoremap <C-l> <C-W>l

" Move around split windows
nnoremap th <C-Pageup>
nnoremap tl <C-Pagedown>
" Open a file under the same directory"
nnoremap <leader>te :tabedit <c-r>=expand("%:p:h")<cr>/
" Move current tab to right position
nnoremap <leader>tm :tabmove<cr>

" Close current buffers
nnoremap <leader>bc :Bclose<cr>
" Close all the buffers
nnoremap <leader>ba :1,1000 bd!<cr>

" Switch CWD to the directory of the open buffer
nnoremap <leader>cd :cd %:p:h<cr>:pwd<cr>

" Useful for editting C source file
inoremap <leader>o <c-o>O


" Specify the behavior when switching between buffers
try
    set switchbuf=useopen,usetab,newtab
    set stal=2
catch
endtry

" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
            \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \ exe "normal! g`\"" |
            \ endif

" Remember info about open buffers on close
set viminfo^=%

" Space to toggle folding
nnoremap <space> za

"" Quicker move head/end of line
"nnoremap H 0
"vnoremap H 0
"nnoremap L $
"vnoremap L $

" Quicker ESC
"inoremap jk <esc>
"" Disable current ESC key to learn new habit
"inoremap <esc> <nop>

""""""""""""""""""""""""""""""
" => Status line
""""""""""""""""""""""""""""""
" Always show the status line
" Powered by powerline
set laststatus=2
let g:Powerline_symbols = 'unicode'

" Format the status line
"set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ %y\ \ CWD:\ %r%{getcwd()}%h\ \ %p%%\ \ %{fugitive#statusline()}
"set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P

"""""""""""""""""""""""""""""""""""
" => Editing mappings
"""""""""""""""""""""""""""""""""""
" Delete trailing white space on save, useful for Python and CoffeeScript ;)
func! DeleteTrailingWS()
    exe "normal mz"
    %s/\s\+$//ge
    exe "normal `z"
endfunc
autocmd BufWrite *.py :call DeleteTrailingWS()
autocmd BufWrite *.coffee :call DeleteTrailingWS()
" Fast type CMakeLists.txt in cmdline
cabbrev CM CMakeLists.txt
" Personal info
iabbrev @@ jeremyrobturtle@gmail.com
iabbrev ccopy Copyright 2014 Yang LIU, all rights reserved.

" Copy all contents
nnoremap <leader>cp mzggyG`z

" New operator mappings
" XXX not practice much
" in parenthesis
onoremap p i(
" to the line contains return
onoremap b /return<cr>
onoremap in( :<c-u>normal! f)vi(<cr>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => vimgrep searching and cope displaying
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" When you press gv you vimgrep after the selected text
vnoremap <silent>gv :call VisualSelection('gv', '')<CR><cr>

" Open vimgrep and put the cursor in the right position
nnoremap <leader>g :vimgrep // **/*.*<left><left><left><left><left><left><left><left>

" When you press <leader>r you can search and replace the selected text
vnoremap <silent><leader>r :call VisualSelection('replace', '')<CR>

" Do :help cope if you are unsure what cope is. It's super useful!
"
" When you search with vimgrep, display your results in cope by doing:
"   <leader>q provided by ListToggle
"
" To go to the next search result do:
"   <leader>n
"
" To go to the previous search results do:
"   <leader>p
"
nnoremap <leader>co ggVGy:tabnew<cr>:set syntax=qf<cr>pgg
nnoremap <leader>n :cn<cr>
nnoremap <leader>p :cp<cr>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Spell checking
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Pressing ,ss will toggle and toggle spell checking
nnoremap <leader>sp :setlocal spell!<cr>

" Shortcuts using <leader>
"  ]s next word
"  [s previous word
"  zg ignore this error
"  z= suggestion

"""""""""""""""""""""""""""""""""""
" => Misc
"""""""""""""""""""""""""""""""""""
" Toggle paste mode on and off
nnoremap <leader>pp :setlocal paste!<cr>:set relativenumber!<cr>:set nu!<cr>

" Entry to temporary snippets
nnoremap <leader>ts :tabedit ~/.vim/bundle/USsnippets/UltiSnips/all.snippets<cr>
" add entry for snippets for current filetype
nnoremap <leader>tf :tabedit ~/.vim/bundle/USsnippets/UltiSnips/<c-r>=&ft<cr>.snippets

let g:myvimrc = "~/git/linux_config/.vimrc"
" Entry to my .vimrc
nnoremap <leader><leader>v :silent exe "tabedit ".g:myvimrc<cr>
" Refresh settings
nnoremap <leader><leader>s :source $MYVIMRC<cr>

" TODO wrap `tabedit` as func: if it's a empty buffer, open it directly
"      then replace all `tabedit` cmd

" fast map of c-x,c-f
inoremap <leader>r <c-x><c-f>

" fast map of :cd
nnoremap cd :cd 
nnoremap cm :!cmake

" Emacs like movement in insert mode"
func! Append()
    normal! l
    if col('.') >= col('$') - 1
        startinsert!
    else
        startinsert
        normal! l
    endif
endfunc

inoremap <c-f> <Esc>:call Append()<cr>
inoremap <c-b> <Esc>:startinsert<cr>

" System clipboard relative
set clipboard^=unnamed

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Helper functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
function! CmdLine(str)
    exe "menu Foo.Bar :" . a:str
    emenu Foo.Bar
    unmenu Foo
endfunction 

function! VisualSelection(direction, extra_filter) range
    let l:saved_reg = @"
    execute "normal! vgvy"

    let l:pattern = escape(@", '\\/.*$^~[]')
    let l:pattern = substitute(l:pattern, "\n$", "", "")

    if a:direction == 'b'
        execute "normal ?" . l:pattern . "^M"
    elseif a:direction == 'gv'
        call CmdLine("vimgrep " . '/'. l:pattern . '/' . ' **/*.*' . a:extra_filter)
    elseif a:direction == 'replace'
        call CmdLine("%s" . '/'. l:pattern . '/')
    elseif a:direction == 'f'
        execute "normal /" . l:pattern . "^M"
    endif

    let @/ = l:pattern
    let @" = l:saved_reg
endfunction


" Returns true if paste mode is enabled
function! HasPaste()
    if &paste
        return 'PASTE MODE  '
    en
    return ''
endfunction

" Don't close window, when deleting a buffer
command! Bclose call <SID>BufcloseCloseIt()
function! <SID>BufcloseCloseIt()
    let l:currentBufNum = bufnr("%")
    let l:alternateBufNum = bufnr("#")

    if buflisted(l:alternateBufNum)
        buffer #
    else
        bnext
    endif

    if bufnr("%") == l:currentBufNum
        new
    endif

    if buflisted(l:currentBufNum)
        execute("bdelete! ".l:currentBufNum)
    endif
endfunction

"""""""""""""""""""""""""""""""""""
" => Plugins configurations
"""""""""""""""""""""""""""""""""""
" Use ranger as vim's file chooser
fun! RangerChooser()
    "silent !ranger --choosefile=/tmp/chosenfile $([ -z '%' ] && echo $(pwd) || dirname %)
    silent !ranger --choosefile=/tmp/chosenfile '%:p:h'
    if filereadable('/tmp/chosenfile')
        exec 'edit ' . system('cat /tmp/chosenfile')
        call system('rm /tmp/chosenfile')
    endif
    redraw!
endfun
nnoremap <leader>e :call RangerChooser()<CR>

" Vundle
" Brief help
" :BundleList		- list configured bundles
" :BundleInstall(!)	- install(update) bundles
" :BundleSearch(!) foo	- search(or refresh cache first) for foo
" :BundleClean(!)	- confirm(or auto-approve) removal of unused bundles
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
" let Vundle manage Vundle
" required
Bundle 'gmarik/vundle'
" My bundles here:
"

""""""""""""""""""""""""""
" Programming
""""""""""""""""""""""""""
" symatics check
Bundle 'scrooloose/syntastic'
" facility to syntastic, open llist quickly
Bundle 'Valloric/ListToggle'
" git wrapper
Bundle 'tpope/vim-fugitive'
" fugitive the Git wrapper
nnoremap gs :Gstatus<cr>
nnoremap gl :Gllog<cr>
nnoremap gpu :Git push<cr>
" Show diff on current file
Bundle 'airblade/vim-gitgutter'

" Vim status bar
Bundle 'vim-airline/vim-airline'
if !exists('g:airline_symbols')
    let g:airline_symbols={}
endif
let g:airline_section_b = '%{strftime("%c")}'
let g:airline_section_y = 'BN:%{bufnr("%")}'
"let g:airline_left_sep = '▶'
"let g:airline_left_alt_sep = '❯'
"let g:airline_right_sep = '◀'
"let g:airline_right_alt_sep = '❮'
"let g:airline_symbols.linenr = '¶'
"let g:airline_symbols.branch = '⎇'
" 开启tabline
let g:airline#extensions#tabline#enabled = 1
" tabline中当前buffer两端的分隔符"
let g:airline#extensions#tabline#left_sep = ' '
"" tabline为激活的buffer的两端字符
let g:airline#extensions#tabline#left_alt_sep = '|'
"" tabline中buffer显示编号"
"let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline#extensions#buffline#enabled = 1
let g:airline#extensions#bufferline#overwrite_variables = 1
"" airline主题
let g:airline_theme = 'powerlineish' 


"YouCompleteMeeeeeee!!!!!!!!
Bundle 'Valloric/YouCompleteMe'
" Try minimize delay using YCM
set nocursorline
let loaded_matchparen = 1

" YouCompleteMe
nnoremap <leader>jd :YcmCompleter GoToDefinitionElseDeclaration<CR>
"let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
" Do not ask when starting vim
let g:ycm_confirm_extra_conf = 0
let g:syntastic_always_populate_loc_list = 1

""""""" c/c++ jump support
" header/source jump
Bundle 'a.vim'
" Commenter
Bundle 'scrooloose/nerdcommenter'
Bundle 'DoxygenToolkit.vim'
let g:load_doxygen_syntax=1
let g:DoxygenToolkit_authorName="Yang Leo"
nnoremap <leader>do :Dox<cr>

"" auto save/restore folding of file
" FIXME not fixed the lopen
augroup restore_folding
    au BufWinLeave ?* mkview
    au BufWinEnter ?* silent loadview
augroup END

" Try to debug it
Bundle 'robturtle/cmake.vim' 
let g:cmake_use_vimux = 1
" Make and show compile error messages
nnoremap <leader>m :silent make\|redraw!\|cc<CR>
""""""""""""""""""""""""""
" End of Programming
""""""""""""""""""""""""""

""""""""""""""""""""""""""
" File finder
""""""""""""""""""""""""""
Bundle 'kien/ctrlp.vim'
" Ctrlp.vim
" I have many symlinks to git repos
let g:ctrlp_follow_symlinks = 1
" Sometimes I wanna open hidden files
let g:ctrlp_show_hidden = 1
" Symlinks may disturb my working on git
let g:ctrlp_switch_buffer = 0

""""""""""""""""""""""""""
" Misc
""""""""""""""""""""""""""
" Vim utilities
Bundle 'L9'
" Statusline utility
Bundle 'Lokaltog/powerline'
" Format table like contents
Bundle 'Tabular'
" Tabular
nnoremap <leader>f :Tabularize /=<cr>
nnoremap <leader>df xP:Tabularize /<C-R>-<CR>
vnoremap <leader>df xP:Tabularize /<C-R>-<CR>
" Tmux integration
Bundle 'benmills/vimux'
" Using this to run shell commands instead of `:!`
nnoremap <Leader>vp :VimuxPromptCommand<CR>
" Run last command executed by VimuxRunCommand
nnoremap <Leader>vl :VimuxRunLastCommand<CR>
" Inspect runner pane map
nnoremap <Leader>vi :VimuxInspectRunner<CR>
" Close vim tmux runner opened by VimuxRunCommand
nnoremap <Leader>vq :VimuxCloseRunner<CR>
" Interrupt any command running in the runner pane map
nnoremap <Leader>vs :VimuxInterruptRunner<CR>
" Zoom the tmux runner page
nnoremap <Leader>vz :VimuxZoomRunner<CR>
" Let tmux run execute the file according to filetype
"nnoremap <leader>vr :call VimuxRunCommand(b:runprg)<CR>
nnoremap <leader>vr :call TryRunFile()<CR>
func! TryRunFile()
    if exists('b:runprg')
        if b:runprg =~ "^:"
            exec b:runprg
        else
            call VimuxRunCommand(b:runprg)
        endif
    else
        echo "TryRunFile: b:runprg not set!"
    endif
endfunc


" Quick test for ACM like problems
nnoremap <leader>vt :call TestACM()<CR>
func! TestACM()
python << EOF
import vim
from itertools import izip
from subprocess import Popen, PIPE, STDOUT
from os.path import exists

exc = vim.eval("expand('%:p:r').'.elf'")
if not exists(exc):
    vim.command("echo('Targe not found! Compile your file first.')")
else:
    infname = vim.eval("expand('%:p:r').'.in'")
    outfname = vim.eval("expand('%:p:r').'.out'")

    for input_, output_ in izip(open(infname), open(outfname)):

        p = Popen([exc], stdout=PIPE, stdin=PIPE, stderr=STDOUT)
        out = p.communicate(input=input_)[0]

        if out != output_:
            msg="Test failed! Input: {} Expect: {} Actually: {}".format(input_, output_, out)
            vim.command("echom('%s')" % msg)
        else:
            msg="Pass"
            vim.command("echo('%s')" % msg)
EOF
endfunc

" Quick open the test cases
nnoremap <leader>vc :call OpenTestFile()<CR>
func! OpenTestFile()
    if &ft == "c" || &ft == "cpp"
        vs
        sp
        exec ":e ".expand("%:p:r").".in"
        wincmd j
        exec ":e ".expand("%:p:r").".out"
    elseif &ft == "scala"
        let l:d = substitute(expand("%:p"), "main", "test", "")
        let l:d = substitute(d, ".scala$", "Suite.scala", "")
        exec ":vs " . l:d
    endif
endfunc

""""""""""""""""""""""""""
" Sniiiippets!!!
""""""""""""""""""""""""""
Bundle 'UltiSnips'
" UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = '<c-j>'
let g:ultisnips_java_brace_style = "nl"
" My own snippets
Bundle 'robturtle/USsnippets'

" Move around
Bundle 'Lokaltog/vim-easymotion'
" Flowy simulation
"Bundle 'laoyang945/vimflowy'
" Chinese input method
"Bundle 'vimim/vimim'
" Window manager
Bundle 'winmanager'
" TODO A better win manager"
" winManager
let g:winManagerWindowLayout="FileExplorer,BufExplorer,TagList"
let g:winManagerWidth=30
let g:defaultExplorer=0
nnoremap wm :WMToggle<cr>

" Modify surrounding tag/'/"/(/[, etc.
Bundle 'tpope/vim-surround'
" Auto complete brackets
Bundle 'Raimondi/delimitMate'
Bundle 'Shougo/vimproc'
" Similar with ctrl-p
Bundle 'Shougo/unite.vim'
" Calendar
Bundle 'mattn/calendar-vim'
""""""""""""""""""""""""""
" End of Misc
""""""""""""""""""""""""""

""""""""""""""""""""""""""
" Colors
""""""""""""""""""""""""""
Bundle 'altercation/vim-colors-solarized'
Bundle 'kien/rainbow_parentheses.vim'
"rainbow_parentheses
let g:rbpt_colorpairs = [
\ ['brown', 'RoyalBlue3'],
\ ['Darkblue', 'SeaGreen3'],
\ ['Darkgray', 'DarkOrchid3'],
\ ['darkgreen', 'firebrick3'],
\ ['darkcyan', 'RoyalBlue3'],
\ ['darkred', 'SeaGreen3'],
\ ['darkmagenta', 'DarkOrchid3'],
\ ['brown', 'firebrick3'],
\ ['gray', 'RoyalBlue3'],
\ ['Darkblue', 'SeaGreen3'],
\ ['darkmagenta', 'DarkOrichd3'],
\ ['Darkblue', 'firebrick3'],
\ ['darkgreen', 'RoyalBlue3'],
\ ['darkcyan', 'SeaGreen3'],
\ ['darkred', 'DarkOrichid3'],
\ ['red', 'firebrick3'],
\ ]
let g:rbpt_max = 16
let g:rbpt_loadcmd_toggle = 0
"au VimEnter * RainbowParenthesesToggle
"au Syntax * RainbowParenthesesLoadRound
"au Syntax * RainbowParenthesesLoadSquare
"au Syntax * RainbowParenthesesLoadBraces

"Bundle 'Yggdroot/indentLine'
" indentLine
let g:indentLine_noConcealCursor = 1
let g:indentLine_color_term = 0
let g:indentLine_char = '|'

"Write/post blog
Bundle 'parkr/vim-jekyll'
""""""""""""""""""""""""""
" End of Color
""""""""""""""""""""""""""

""""""""""""""""""""""""""
" Filetype support
""""""""""""""""""""""""""
"Bundle 'plasticboy/vim-markdown'
Bundle 'tpope/vim-liquid'
"Bundle 'PProvost/vim-markdown-jekyll'
Bundle 'python.vim'
Bundle 'pangloss/vim-javascript'
Bundle 'php.vim--Garvin'
Bundle 'eagletmt/ghcmod-vim'
Bundle 'eagletmt/neco-ghc'
" enable auto-completion for Haskell using YCM
augroup hs_settings
    au BufRead,BufNewFile *.hs setlocal omnifunc=necoghc#omnifunc
    au BufRead,BufNewFile *.hs let g:necoghc_enable_detailed_browse = 1
augroup END
Bundle 'greyblake/vim-preview'

Bundle 'derekwyatt/vim-scala'

" Configuration of Eclim

" It's slow so let's do it manually
let g:EclimScalaValidate = 0
" YCM support
let g:EclimCompletionMethod = 'omnifunc'
" todo support
let g:EclimTodoSearchExtensions = ['java', 'py', 'php', 'jsp', 'xml', 'html', 'scala']

" Java convenience
augroup set_java
    au Filetype java nnoremap <leader>im :JavaImport<cr>
augroup END

" HTML5
Bundle 'othree/html5.vim'

" Html writer
""""""""""""""""""""""""""
"zen coding like plugin
Bundle 'mattn/emmet-vim'
"let g:user_zen_leader_key = '<c-e>'

filetype plugin indent on " required
syntax on
" Vundle end

"YouCompleteMe配置
let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'   "配置默认的ycm_extra_conf.py
nnoremap <leader>jd :YcmCompleter GoToDefinitionElseDeclaration<CR>   "按,jd 会跳转到定义
let g:ycm_confirm_extra_conf=0    "打开vim时不再询问是否加载ycm_extra_conf.py配置
let g:ycm_collect_identifiers_from_tag_files = 1 "使用ctags生成的tags文件"


set completeopt=longest,menu "让Vim的补全菜单行为与一般IDE一致(参考VimTip1228)
autocmd InsertLeave * if pumvisible() == 0|pclose|endif "离开插入模式后自动关闭预览窗口
inoremap <expr> <CR>       pumvisible() ? "\<C-y>" : "\<CR>"    "回车即选中当前项
"上下左右键的行为 会显示其他信息
inoremap <expr> <Down>     pumvisible() ? "\<C-n>" : "\<Down>"
inoremap <expr> <Up>       pumvisible() ? "\<C-p>" : "\<Up>"
inoremap <expr> <PageDown> pumvisible() ? "\<PageDown>\<C-p>\<C-n>" : "\<PageDown>"
inoremap <expr> <PageUp>   pumvisible() ? "\<PageUp>\<C-p>\<C-n>" : "\<PageUp>"

"youcompleteme  默认tab  s-tab 和自动补全冲突
let g:ycm_key_list_select_completion=['<c-n>']
let g:ycm_key_list_select_completion = ['<Down>']
let g:ycm_key_list_previous_completion=['<c-p>']
let g:ycm_key_list_previous_completion = ['<Up>']
let g:ycm_confirm_extra_conf=0 "关闭加载.ycm_extra_conf.py提示

let g:ycm_collect_identifiers_from_tags_files=1 " 开启 YCM 基于标签引擎
let g:ycm_min_num_of_chars_for_completion=2 " 从第2个键入字符就开始罗列匹配项
let g:ycm_cache_omnifunc=0  " 禁止缓存匹配项,每次都重新生成匹配项
let g:ycm_seed_identifiers_with_syntax=1    " 语法关键字补全
nnoremap <F5> :YcmForceCompileAndDiagnostics<CR>    "force recomile with syntastic
nnoremap <leader>lo :lopen<CR> "open locationlist
nnoremap <leader>lc :lclose<CR>   "close locationlist
inoremap <leader><leader> <C-x><C-o>
"在注释输入中也能补全
let g:ycm_complete_in_comments = 1
"在字符串输入中也能补全
let g:ycm_complete_in_strings = 1
"注释和字符串中的文字也会被收入补全
let g:ycm_collect_identifiers_from_comments_and_strings = 0

nnoremap <leader>jd :YcmCompleter GoToDefinitionElseDeclaration<CR> " 跳转到定义处]"

"YCM默认不会补全全局函数或系统函数，当输入函数前几个字母时按Ctrl+i即可手动调用函数的补全
let g:ycm_key_invoke_completion = '<C-i>'
